

$nodes = 5

Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"

    (0..($nodes - 1)).each do |i|
        config.vm.define name="node-#{i}", primary: (i == 0), autostart: (i == 0) do |node|
            node.vm.hostname = name
            node.vm.network "private_network", ip: "192.168.50.#{10+i}"

            node.vm.provision "shell", path: "provision.sh", env: {"LOCAL_IP" => "192.168.50.#{10+i}", "ETCD_ENDPOINT" => "http://192.168.50.10:2379"}
        end
    end
end