// Code generated by protoc-gen-go.
// source: topic.proto
// DO NOT EDIT!

/*
Package topic is a generated protocol buffer package.

It is generated from these files:
	topic.proto

It has these top-level messages:
	GetTopicRequest
	GetTopicResponse
*/
package topic

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetTopicRequest struct {
	TopicId int64 `protobuf:"varint,1,opt,name=topic_id,json=topicId" json:"topic_id,omitempty"`
}

func (m *GetTopicRequest) Reset()                    { *m = GetTopicRequest{} }
func (m *GetTopicRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTopicRequest) ProtoMessage()               {}
func (*GetTopicRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetTopicRequest) GetTopicId() int64 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

type GetTopicResponse struct {
	TopicId int64  `protobuf:"varint,1,opt,name=topic_id,json=topicId" json:"topic_id,omitempty"`
	Subject string `protobuf:"bytes,2,opt,name=subject" json:"subject,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
}

func (m *GetTopicResponse) Reset()                    { *m = GetTopicResponse{} }
func (m *GetTopicResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTopicResponse) ProtoMessage()               {}
func (*GetTopicResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetTopicResponse) GetTopicId() int64 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *GetTopicResponse) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *GetTopicResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*GetTopicRequest)(nil), "topic.GetTopicRequest")
	proto.RegisterType((*GetTopicResponse)(nil), "topic.GetTopicResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Topic service

type TopicClient interface {
	// Sums two integers.
	GetTopic(ctx context.Context, in *GetTopicRequest, opts ...grpc.CallOption) (*GetTopicResponse, error)
}

type topicClient struct {
	cc *grpc.ClientConn
}

func NewTopicClient(cc *grpc.ClientConn) TopicClient {
	return &topicClient{cc}
}

func (c *topicClient) GetTopic(ctx context.Context, in *GetTopicRequest, opts ...grpc.CallOption) (*GetTopicResponse, error) {
	out := new(GetTopicResponse)
	err := grpc.Invoke(ctx, "/topic.Topic/GetTopic", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Topic service

type TopicServer interface {
	// Sums two integers.
	GetTopic(context.Context, *GetTopicRequest) (*GetTopicResponse, error)
}

func RegisterTopicServer(s *grpc.Server, srv TopicServer) {
	s.RegisterService(&_Topic_serviceDesc, srv)
}

func _Topic_GetTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicServer).GetTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topic.Topic/GetTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicServer).GetTopic(ctx, req.(*GetTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Topic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "topic.Topic",
	HandlerType: (*TopicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTopic",
			Handler:    _Topic_GetTopic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "topic.proto",
}

func init() { proto.RegisterFile("topic.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xc9, 0x2f, 0xc8,
	0x4c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x74, 0xb8, 0xf8, 0xdd,
	0x53, 0x4b, 0x42, 0x40, 0xec, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x49, 0x2e, 0x0e,
	0xb0, 0x5c, 0x7c, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x3b, 0x98, 0xef, 0x99,
	0xa2, 0x94, 0xc8, 0x25, 0x80, 0x50, 0x5d, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x8a, 0x47, 0xb9, 0x90,
	0x04, 0x17, 0x7b, 0x71, 0x69, 0x52, 0x56, 0x6a, 0x72, 0x89, 0x04, 0x13, 0x50, 0x86, 0x33, 0x08,
	0xc6, 0x05, 0xc9, 0x24, 0xe7, 0xe7, 0x95, 0xa4, 0xe6, 0x95, 0x48, 0x30, 0x43, 0x64, 0xa0, 0x5c,
	0x23, 0x37, 0x2e, 0x56, 0xb0, 0xf9, 0x42, 0xb6, 0x5c, 0x1c, 0x30, 0xbb, 0x84, 0xc4, 0xf4, 0x20,
	0x4e, 0x47, 0x73, 0xaa, 0x94, 0x38, 0x86, 0x38, 0xc4, 0x51, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x6f,
	0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x22, 0x0a, 0xad, 0x52, 0xf5, 0x00, 0x00, 0x00,
}
